[Network]
Address = ':19132'

[Server]
Name = 'Dragonfly Server'
ShutdownMessage = "<red>Moyai has restarted - please re-join when it's back up!</red>"
AuthEnabled = true
JoinMessage = '%v has joined the game'
QuitMessage = '%v has left the game'

[World]
SaveData = true
Folder = 'assets/world'

[Players]
MaxCount = 0
MaximumChunkRadius = 8
SaveData = false
Folder = 'players'

[Resources]
AutoBuildPack = true
Folder = 'assets/resources'
Required = false

[Moyai]
Tebex = 'f2329e8813bc7bb5952b79692c61044320c3f1eb'

[Oomph]
Port = 19132
CombatMode = 2
MovementMode = 2
