[Network]
Address = ':19132'

[Server]
Name = 'Dragonfly Server'
ShutdownMessage = 'Server closed.'
AuthEnabled = true
JoinMessage = '%v has joined the game'
QuitMessage = '%v has left the game'

[World]
SaveData = true
Folder = 'assets/world'

[Players]
MaxCount = 0
MaximumChunkRadius = 32
SaveData = false
Folder = 'players'

[Resources]
AutoBuildPack = true
Folder = 'assets/resources'
Required = false

[Oomph]
Port = 19132
CombatMode = 2
MovementMode = 2
